sudo: required

language: elixir
elixir:
  - 1.6.5

services:
  - docker

install:
  - docker-compose build

script:
  - docker-compose run mssqlex mix compile --warnings-as-errors
  - docker-compose run mssqlex mix coveralls.travis

after_script:
  - mix local.hex --force
  - mix local.rebar --force
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
