
language: elixir
elixir:
  - 1.8

services:
  - docker

install:
  - docker-compose build

script:
  - docker-compose run mssql_ecto mix compile --warnings-as-errors
  - docker-compose run mssql_ecto mix coveralls.travis

after_script:
  - mix local.hex --force
  - mix local.rebar --force
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
